Handles Pyramid path regex and subpaths
Cornices/cornice.ext.swagger pull request #70
Opened 2017-04-08 22:07 UTC by gabisurita

Fixes: #68 
Related to: https://github.com/Kinto/kinto/issues/1180

Support path regex and subpath matching in Pyramid routes. 

Considerations:
- Subpaths are considered regular path attributes.
- Regex is used as the attribute pattern on the swagger documentation

Notes:
- Traverse and subpath are very primitive and only allow the definitions to be valid. Maybe we can try a better approach. Ideas?

r? @glasserc

2017-04-09 16:03 UTC, glasserc requested changes
Thanks for taking the time to read through all the Pyramid documentation. My head started to spin by the time I got to "There are only four real differences between a purely traversal-based application and a hybrid application".

I think the approach taken here is a good one. Maybe I didn't understand the question but I don't think we can really offer much for `*traverse` and `*subpath` without a lot of complexity in doing traversals ourselves. I'd prefer to leave this alone until we get a feature request with a concrete use case.

I'm not an expert on Pyramid by any means so feel free to correct me if my understanding of `*subpath` and `*traverse` in my review comments is wrong :)

2017-04-09 16:03 UTC, glasserc commented on cornice_swagger/converters/parameters.py
> +            if name.find(subpath_marker) > 0:
Should this be `>= 0`? Or should we just use `subpath_marker in name`?

2017-04-09 16:03 UTC, glasserc commented on cornice_swagger/converters/parameters.py
> +                name = subpath_marker[1:]
Is it possible to have a `pattern` for `*subpath` or `*traversal`? Should we just return here to make it obvious that the `pattern` part of this function isn't relevant, or maybe move this stanza to the top of the function?

2017-04-09 16:03 UTC, glasserc commented on cornice_swagger/swagger.py
> +                       if comp.startswith('{') and comp.endswith('}')]
The documentation at http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hybrid.html makes it seem like `*traverse` and `*subpath` don't occur in `{`/`}` but just show up at the end of the path.

2017-04-09 16:03 UTC, glasserc commented on tests/test_parameter_handler.py
> +        self.assertEqual(sorted(names), sorted(expected))
Nice; maybe we should add a test to verify that the patterns get captured too?

2017-04-10 01:39 UTC, gabisurita commented on cornice_swagger/converters/parameters.py
> +                name = subpath_marker[1:]
I'm not sure about this one, but I think we can just ignore the pattern in such cases.

2017-04-10 01:57 UTC, gabisurita commented on cornice_swagger/swagger.py
> +        for subpath_marker in ('*subpath', '*traverse'):
I think we can do this here if we assume that subpaths only occur outside `{ }`.

2017-04-10 02:00 UTC, gabisurita commented
> I think the approach taken here is a good one. Maybe I didn't understand the question but I don't think we can really offer much for *traverse and *subpath without a lot of complexity in doing traversals ourselves. I'd prefer to leave this alone until we get a feature request with a concrete use case.

I agree, by this approach I just want to make sure that the result is valid. and that we do include a way to provide the subpath on the documentation.

2017-04-10 02:37 UTC, gabisurita commented on cornice_swagger/swagger.py
> +            path = path.replace(subpath_marker, '{subpath}')
If we assume that `subpath` and `traverse` are always outside `{ .* }` we can do something like this.

2017-04-10 14:27 UTC, glasserc approved these changes
Very slick!

2017-04-11 01:10 UTC, merged